### ISSUE TITLE
Request: make the search case-insensitive

### ISSUE THREAD

**Issue by CDB-Man** [fish-face/quasselgrep#16]
Currently the search is finicky when it comes to casing. The easiest way to deal with this is to ignore case altogether.

**Comment by markasoftware** [comment]
Did you figure it out?

**Comment by CDB-Man** [comment]
> Did you figure it out?

Nope, I never did.  Looking back, I'm not sure why I closed the issue either, so I'm reopening it.

**Comment by noahajac** [comment]
I made pull request #17 that should resolve this issue.
