### ISSUE TITLE
Provide a setup.py?

### ISSUE THREAD

**Issue by TC01** [fish-face/quasselgrep#4]
Any chance you could provide a Python distutils/setuptools file to make quasselgrep a bit more easily installable?

**Comment by fish-face** [comment]
Good idea, but I've never actually written one before. If you know how to make them, a PR would be welcome - I can answer any questions. Otherwise I'll get to it at some point.

**Comment by TC01** [comment]
Oh, sure, I'd be happy to. I'll take a look tomorrow.
