### ISSUE TITLE
Support python 2 and 3

### ISSUE THREAD

**Issue by fish-face** [fish-face/quasselgrep#7]

**Comment by Scimmia22** [comment]
Any progress on this? Looking at 2to3, it doesn't appear that the changes would need to be too extensive, but we both know that 2to3 doesn't tell the whole story.

**Comment by Scimmia22** [comment]
It looks simple enough I would even take a crack at it myself, but I'd do a full conversion to py3 and drop py2 support. I don't see the point in supporting a dead dialect. If that's something you'd accept, let me know.

**Comment by fish-face** [comment]
Fixed in `f0124fa`
